// Code Generation Test Suite
//
// This package serves as a test bed for verifying codex-rs can complete
// production-grade code development tasks including:
// 1. Adding new functions with proper signatures and tests
// 2. Fixing bugs in existing code
// 3. Refactoring code while maintaining functionality
// 4. Performance validation

fn main() {
    println!("Code Generation Test Suite - Demo");
    println!("==================================");

    // Test basic math operations
    let a = 42.0;
    let b = 8.0;

    println!("a = {}, b = {}", a, b);
    println!("add(a, b) = {}", add(a, b));
    println!("subtract(a, b) = {}", subtract(a, b));
    println!("multiply(a, b) = {}", multiply(a, b));
    println!("divide(a, b) = {}", divide(a, b));
    println!("power(a, 2) = {}", power(a, 2.0));
    println!("sqrt(16) = {}", sqrt(16.0));
}

// Basic arithmetic operations
fn add(a: f64, b: f64) -> f64 {
    a + b
}

fn subtract(a: f64, b: f64) -> f64 {
    a - b
}

fn multiply(a: f64, b: f64) -> f64 {
    a * b
}

fn divide(a: f64, b: f64) -> f64 {
    if b == 0.0 {
        panic!("Division by zero");
    }
    a / b
}

// Advanced math operations (to be generated by codex)
fn power(base: f64, exp: f64) -> f64 {
    base.powf(exp)
}

fn sqrt(x: f64) -> f64 {
    if x < 0.0 {
        panic!("Square root of negative number");
    }
    x.sqrt()
}

// Utility functions (candidates for refactoring tests)
fn clamp(value: f64, min: f64, max: f64) -> f64 {
    if value < min {
        min
    } else if value > max {
        max
    } else {
        value
    }
}

fn lerp(a: f64, b: f64, t: f64) -> f64 {
    a + (b - a) * t
}
